module.exports = [
  { isoCode: " ", symbol: "$", name: "select currency" },
  { isoCode: "usd", symbol: "$", name: "US Dollar" },
  { isoCode: "cad", symbol: "CA$", name: "Canadian Dollar" },
  { isoCode: "eur", symbol: "€", name: "Euro" },
  { isoCode: "aed", symbol: "AED", name: "United Arab Emirates Dirham" },
  { isoCode: "afn", symbol: "Af", name: "Afghan Afghani" },
  { isoCode: "all", symbol: "ALL", name: "Albanian Lek" },
  { isoCode: "amd", symbol: "AMD", name: "Armenian Dram" },
  { isoCode: "ars", symbol: "AR$", name: "Argentine Peso" },
  { isoCode: "ang", symbol: "ƒ", name: "Netherlands Antilles guilder" },
  { isoCode: "aoa", symbol: "Kz", name: "Angolan kwanza" },
  { isoCode: "ars", symbol: "$", name: "Argentine peso" },
  { isoCode: "aud", symbol: "AU$", name: "Australian Dollar" },
  { isoCode: "awg", symbol: "ƒ", name: "Aruban florin" },
  { isoCode: "azn", symbol: "man.", name: "Azerbaijani Manat" },
  {
    isoCode: "bam",
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
  },
  { isoCode: "bbd", symbol: "BBD$", name: "Barbadian dollar" },
  { isoCode: "bdt", symbol: "Tk", name: "Bangladeshi Taka" },
  { isoCode: "bgn", symbol: "BGN", name: "Bulgarian Lev" },
  //   { isoCode: "bhd", symbol: "BD", name: "Bahraini Dinar" },
  { isoCode: "bif", symbol: "FBu", name: "Burundian Franc" },
  { isoCode: "bmd", symbol: "$", name: "Bermudian dollar" },
  { isoCode: "bnd", symbol: "BN$", name: "Brunei Dollar" },
  { isoCode: "bob", symbol: "Bs", name: "Bolivian Boliviano" },
  { isoCode: "brl", symbol: "R$", name: "Brazilian Real" },
  { isoCode: "bsd", symbol: "B$", name: "Bahamian dollar" },
  { isoCode: "bwp", symbol: "BWP", name: "Botswanan Pula" },
  { isoCode: "byn", symbol: "Br", name: "Belarusian Ruble" },
  { isoCode: "bzd", symbol: "BZ$", name: "Belize Dollar" },
  { isoCode: "cdf", symbol: "CDF", name: "Congolese Franc" },
  { isoCode: "chf", symbol: "CHF", name: "Swiss Franc" },
  { isoCode: "clp", symbol: "CL$", name: "Chilean Peso" },
  { isoCode: "cny", symbol: "CN¥", name: "Chinese Yuan" },
  { isoCode: "cop", symbol: "CO$", name: "Colombian Peso" },
  { isoCode: "crc", symbol: "₡", name: "Costa Rican Colón" },
  { isoCode: "cve", symbol: "CV$", name: "Cape Verdean Escudo" },
  { isoCode: "czk", symbol: "Kč", name: "Czech Koruna" },
  { isoCode: "djf", symbol: "Fdj", name: "Djiboutian Franc" },
  { isoCode: "dkk", symbol: "Dkr", name: "Danish Krone" },
  { isoCode: "dop", symbol: "RD$", name: "Dominican Peso" },
  { isoCode: "dzd", symbol: "DA", name: "Algerian Dinar" },
  //   { isoCode: "eek", symbol: "Ekr", name: "Estonian Kroon" },
  { isoCode: "egp", symbol: "EGP", name: "Egyptian Pound" },
  //   { isoCode: "ern", symbol: "Nfk", name: "Eritrean Nakfa" },
  { isoCode: "etb", symbol: "Br", name: "Ethiopian Birr" },
  { isoCode: "fjd", symbol: "FJ$", name: "Fijian dollar" },
  { isoCode: "fkp", symbol: "£", name: "Falkland Islands pound" },
  { isoCode: "gbp", symbol: "£", name: "British Pound Sterling" },
  { isoCode: "gel", symbol: "GEL", name: "Georgian Lari" },
  //   { isoCode: "ghs", symbol: "GH₵", name: "Ghanaian Cedi" },
  { isoCode: "gip", symbol: "£", name: "Gibraltar pound" },
  { isoCode: "gmd", symbol: "D", name: "Gambian dalasi" },
  { isoCode: "gnf", symbol: "FG", name: "Guinean Franc" },
  { isoCode: "gtq", symbol: "GTQ", name: "Guatemalan Quetzal" },
  { isoCode: "gyd", symbol: "GY$", name: "Guyanese dollar" },
  { isoCode: "hkd", symbol: "HK$", name: "Hong Kong Dollar" },
  { isoCode: "hnl", symbol: "HNL", name: "Honduran Lempira" },
  { isoCode: "hrk", symbol: "kn", name: "Croatian Kuna" },
  { isoCode: "htg", symbol: "G", name: "Haitian gourde" },
  { isoCode: "huf", symbol: "Ft", name: "Hungarian Forint" },
  { isoCode: "idr", symbol: "Rp", name: "Indonesian Rupiah" },
  { isoCode: "ils", symbol: "₪", name: "Israeli New Sheqel" },
  { isoCode: "inr", symbol: "Rs", name: "Indian Rupee" },
  //   { isoCode: "iqd", symbol: "IQD", name: "Iraqi Dinar" },
  //   { isoCode: "irr", symbol: "IRR", name: "Iranian Rial" },
  { isoCode: "isk", symbol: "Ikr", name: "Icelandic Króna" },
  { isoCode: "jmd", symbol: "J$", name: "Jamaican Dollar" },
  //   { isoCode: "jod", symbol: "JD", name: "Jordanian Dinar" },
  { isoCode: "jpy", symbol: "¥", name: "Japanese Yen" },
  { isoCode: "kes", symbol: "Ksh", name: "Kenyan Shilling" },
  { isoCode: "kgs", symbol: "⃀", name: "Kyrgyzstani som" },
  { isoCode: "khr", symbol: "KHR", name: "Cambodian Riel" },
  { isoCode: "kmf", symbol: "CF", name: "Comorian Franc" },
  { isoCode: "krw", symbol: "₩", name: "South Korean Won" },
  //   { isoCode: "kwd", symbol: "KD", name: "Kuwaiti Dinar" },
  { isoCode: "kyd", symbol: "$", name: "Cayman Islands dollar" },
  { isoCode: "kzt", symbol: "KZT", name: "Kazakhstani Tenge" },
  { isoCode: "lak", symbol: "₭N", name: "Lao kip" },
  { isoCode: "lbp", symbol: "L.L.", name: "Lebanese Pound" },
  { isoCode: "lkr", symbol: "SLRs", name: "Sri Lankan Rupee" },
  //   { isoCode: "ltl", symbol: "Lt", name: "Lithuanian Litas" },
  //   { isoCode: "lvl", symbol: "Ls", name: "Latvian Lats" },
  //   { isoCode: "lyd", symbol: "LD", name: "Libyan Dinar" },
  { isoCode: "lrd", symbol: "LD$", name: "Liberian dollar" },
  { isoCode: "lsl", symbol: "L", name: "Lesotho loti" },
  { isoCode: "mad", symbol: "MAD", name: "Moroccan Dirham" },
  { isoCode: "mdl", symbol: "MDL", name: "Moldovan Leu" },
  { isoCode: "mga", symbol: "MGA", name: "Malagasy Ariary" },
  { isoCode: "mkd", symbol: "MKD", name: "Macedonian Denar" },
  { isoCode: "mmk", symbol: "MMK", name: "Myanmar Kyat" },
  { isoCode: "mnt", symbol: "₮", name: "Mongolian tögrög" },
  { isoCode: "mop", symbol: "MOP$", name: "Macanese Pataca" },
  { isoCode: "mro", symbol: "UM", name: "Mauritanian ouguiya" },
  { isoCode: "mur", symbol: "MURs", name: "Mauritian Rupee" },
  { isoCode: "mvr", symbol: ".ރ", name: "Maldivian rufiyaa" },
  { isoCode: "mwk", symbol: "K", name: "Malawian kwacha" },
  { isoCode: "mxn", symbol: "MX$", name: "Mexican Peso" },
  { isoCode: "myr", symbol: "RM", name: "Malaysian Ringgit" },
  { isoCode: "mzn", symbol: "MTn", name: "Mozambican Metical" },
  { isoCode: "nad", symbol: "N$", name: "Namibian Dollar" },
  { isoCode: "ngn", symbol: "₦", name: "Nigerian Naira" },
  { isoCode: "nio", symbol: "C$", name: "Nicaraguan Córdoba" },
  { isoCode: "nok", symbol: "Nkr", name: "Norwegian Krone" },
  { isoCode: "npr", symbol: "NPRs", name: "Nepalese Rupee" },
  { isoCode: "nzd", symbol: "NZ$", name: "New Zealand Dollar" },
  //   { isoCode: "omr", symbol: "OMR", name: "Omani Rial" },
  { isoCode: "pab", symbol: "B/.", name: "Panamanian Balboa" },
  { isoCode: "pen", symbol: "S/.", name: "Peruvian Nuevo Sol" },
  { isoCode: "pgk", symbol: "K", name: "Papua New Guinean kina" },
  { isoCode: "php", symbol: "₱", name: "Philippine Peso" },
  { isoCode: "pkr", symbol: "PKRs", name: "Pakistani Rupee" },
  { isoCode: "pln", symbol: "zł", name: "Polish Zloty" },
  { isoCode: "pyg", symbol: "₲", name: "Paraguayan Guarani" },
  { isoCode: "qar", symbol: "QR", name: "Qatari Rial" },
  { isoCode: "ron", symbol: "RON", name: "Romanian Leu" },
  { isoCode: "rsd", symbol: "din.", name: "Serbian Dinar" },
  { isoCode: "rub", symbol: "RUB", name: "Russian Ruble" },
  { isoCode: "rwf", symbol: "RWF", name: "Rwandan Franc" },
  { isoCode: "sar", symbol: "SR", name: "Saudi Riyal" },
  { isoCode: "sbd", symbol: "SI$", name: "Solomon Islands dollar" },
  { isoCode: "scr", symbol: "₨ /-", name: "Seychellois rupee" },
  //   { isoCode: "sdg", symbol: "SDG", name: "Sudanese Pound" },
  { isoCode: "sek", symbol: "Skr", name: "Swedish Krona" },
  { isoCode: "sgd", symbol: "S$", name: "Singapore Dollar" },
  { isoCode: "shp", symbol: "£", name: "Saint Helena pound" },
  { isoCode: "sll", symbol: "Le", name: "Sierra Leonean leone" },
  { isoCode: "sos", symbol: "Ssh", name: "Somali Shilling" },
  { isoCode: "srd", symbol: "$", name: "Surinamese dollar" },
  { isoCode: "std", symbol: "STD", name: "dóbra" },
  { isoCode: "szl", symbol: "E", name: "Swazi lilangeni" },
  //   { isoCode: "syp", symbol: "SY£", name: "Syrian Pound" },
  { isoCode: "thb", symbol: "฿", name: "Thai Baht" },
  { isoCode: "tjs", symbol: "SM", name: "Tajikistani somoni" },
  //   { isoCode: "tnd", symbol: "DT", name: "Tunisian Dinar" },
  { isoCode: "top", symbol: "T$", name: "Tongan Paʻanga" },
  { isoCode: "try", symbol: "TL", name: "Turkish Lira" },
  { isoCode: "ttd", symbol: "TT$", name: "Trinidad and Tobago Dollar" },
  { isoCode: "twd", symbol: "NT$", name: "New Taiwan Dollar" },
  { isoCode: "tzs", symbol: "TSh", name: "Tanzanian Shilling" },
  { isoCode: "uah", symbol: "₴", name: "Ukrainian Hryvnia" },
  { isoCode: "ugx", symbol: "USh", name: "Ugandan Shilling" },
  { isoCode: "uyu", symbol: "$U", name: "Uruguayan Peso" },
  { isoCode: "uzs", symbol: "UZS", name: "Uzbekistan Som" },
  //   { isoCode: "vef", symbol: "Bs.F.", name: "Venezuelan Bolívar" },
  { isoCode: "vnd", symbol: "₫", name: "Vietnamese Dong" },
  { isoCode: "vuv", symbol: "VT", name: "Vanuatu vatu" },
  { isoCode: "wst", symbol: "WS$", name: "Samoan tālā" },
  { isoCode: "xaf", symbol: "FCFA", name: "CFA Franc BEAC" },
  { isoCode: "xcd", symbol: "$", name: "Eastern Caribbean dollar" },
  { isoCode: "xof", symbol: "CFA", name: "CFA Franc BCEAO" },
  { isoCode: "xpf", symbol: "₣", name: "CFP franc" },
  { isoCode: "yer", symbol: "YR", name: "Yemeni Rial" },
  { isoCode: "zar", symbol: "R", name: "South African Rand" },
  //   { isoCode: "zmk", symbol: "ZK", name: "Zambian Kwacha" },
  //   { isoCode: "zwl", symbol: "ZWL$", name: "Zimbabwean Dollar" },
  { isoCode: "zmw", symbol: "ZK", name: "Zambian kwacha" },
];
